FROM mcr.microsoft.com/dotnet/runtime:9.0 AS base
USER $APP_UID
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["SolarLab.EBoard.Notifications.Worker/SolarLab.EBoard.Notifications.Worker.csproj", "SolarLab.EBoard.Notifications.Worker/"]
RUN dotnet restore "SolarLab.EBoard.Notifications.Worker/SolarLab.EBoard.Notifications.Worker.csproj"
COPY . .
WORKDIR "/src/SolarLab.EBoard.Notifications.Worker"
RUN dotnet build "SolarLab.EBoard.Notifications.Worker.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "SolarLab.EBoard.Notifications.Worker.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SolarLab.EBoard.Notifications.Worker.dll"]
